### ISSUE TITLE
[BUG] Server crash, replacement of ts/js files

### ISSUE THREAD

**Issue by gerod220** [dev2alert/node-samp#1]
[BUG] When ts/js files are being replaced, during server operation and their execution, the server simply crashes. I would like to hot-swap ts/js files in order to change the functionality of the server on the go

**Comment by The2Alert** [comment]
Show me your <code>package.json</code>

**Comment by The2Alert** [comment]
You didn't give me the information I needed. 

I'm closing the topic.
