### ISSUE TITLE
[Q/A] SHA256

### ISSUE THREAD

**Issue by 14837-eng** [dev2alert/node-samp#10]
Есть поддержка SHA256 из клиента 0.3.7 r4?
Или использовать нодовские шифропакеты по типу crypto?

**Comment by The2Alert** [comment]
Вполне можно нодовские использовать, вот <a href="https://www.npmjs.com/package/sha256">пакет</a> из npm например.

**Comment by 14837-eng** [comment]
> Вполне можно нодовские использовать, вот [пакет](https://www.npmjs.com/package/sha256) из npm например.

Окей
