### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by vedran77** [dev2alert/node-samp#2]
Hello I fresh installed everything, and after connect, my server crash. 
I'm using Node v14.16.0, and I just run `npm i` `npm run compile` `npm start`
Here are crash details.

![image](https://user-images.githubusercontent.com/94656982/154750366-6f648f6f-a0f0-4ff1-afc7-01d48fd0964f.png)

**Comment by The2Alert** [comment]
There are two ways to solve this problem:

<h3>1 way</h3>
<p>Use the compilation parameter <code>"emitDecoratorMetadata": true</code>.</p>

<h3>2 way</h3>
<p>Use for example <code>@Import(() => MyContext)</code>, instead of <code>@Import()</code>.</p>

**Comment by The2Alert** [comment]
A bug in the TypeScript starter has been fixed.
