### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by Revalto** [dev2alert/node-samp#4]
ENG:
Hello! I would like to clarify a couple of questions that are very interesting to me:
1. Is multithreading implemented on the side of the server itself? (AMX)
2. Is it possible to use multithreading on the NodeJS side?
3. Why is this library better than the alternative? (https://github.com/AmyrAhmady/samp-node)
4. Are there any measurements of the speed of information exchange between the NodeJS application and the server?
5. How long do you plan to support this library?

I really liked your approach, I'm thinking about using your library, so please answer these questions. 

RU:
Здравствуйте! Хотел бы уточнить пару вопросов, который очень интерисуют меня:
1. Реализована ли многопоточность на стороне самого сервера? (AMX)
2. Возможно ли использовать многопоточность на стороне NodeJS?
3. Чем эта библиотека лучше альтернативы? (https://github.com/AmyrAhmady/samp-node)
4. Есть ли замеры скорости обмена информации NodeJS приложения с сервером ?
5. Как долго планируете поддерживать данную библиотеку?

Мне очень понравился ваш подход, раздумываю о использовании вашей библиотеки, поэтому ответьте пожалуйста на эти вопросы.

**Comment by The2Alert** [comment]
1) Реализована ли многопоточность на стороне самого сервера? 
- Нет.
2) Возможно ли использовать многопоточность на стороне NodeJS?
- Возможно.
3) Чем эта библиотека лучше альтернативы? (https://github.com/AmyrAhmady/samp-node)
<ul>
    <li>Взаимодействие с API сервера осуществляется через классы и аксессоры (get/set), что сокращает время написания кода.</li>
    <li><a href="https://github.com/dev2alert/node-samp/wiki/Context-API">Context API</a></li>
    <li><a href="https://github.com/dev2alert/node-samp-cli">CLI</a></li>
    <li>Поддержка API популярных плагинов.</li>
    <li>Тестирование <a href="https://jestjs.io/">Jest</a>, которое скоро будет добавлено в поддержку.</li>
</ul>

4) Есть ли замеры скорости обмена информации NodeJS приложения с сервером?
- Нету. Скоро будет добавлена поддержка тестирования Jest, где вы сможете замерять скорость выполнения.
5) Как долго планируете поддерживать данную библиотеку?
- Все зависит от поддержки сообщества и от моего успеха в данной области.
