### ISSUE TITLE
env

### ISSUE THREAD

**Issue by Revalto** [dev2alert/node-samp#6]
При попытке запустить сервер выпадает такое сообщение:
```
/usr/bin/env: «node\r»: Нет такого файла или каталога
```

uname -a
```
Linux revalto 5.10.0-12-amd64 #1 SMP Debian 5.10.103-1 (2022-03-07) x86_64 GNU/Linux
```

**Comment by The2Alert** [comment]
Preliminary requirements:

[Node.js](https://nodejs.org/en/download/) >= <code>16.13.2</code>
