### ISSUE TITLE
Проблемы с запуском.

### ISSUE THREAD

**Issue by 14837-eng** [dev2alert/node-samp#7]
Привет. Скопировал стартер, установил пакеты и вот. 

![image](https://user-images.githubusercontent.com/56313646/188290947-0037a9d2-879a-4592-b524-6b9e5f1863cc.png)

Версии ноды и npm
![image](https://user-images.githubusercontent.com/56313646/188291014-e0cb7bf6-b1da-4468-963b-8dbeafacd06a.png)

**Comment by The2Alert** [comment]
Попробуй установить class-transformer:
```
npm i class-transformer
```

**Comment by 14837-eng** [comment]
> Попробуй установить class-transformer:
> 
> ```
> npm i class-transformer
> ```

Помогло. Спасибо.

**Comment by The2Alert** [comment]
Почаще отликайся, если будут возникать проблемы.
