### ISSUE TITLE
[Q/A] Обработка диалогов.

### ISSUE THREAD

**Issue by 14837-eng** [dev2alert/node-samp#9]
Как обработать диалог с определенным идентификатором ?

В доке пример с обработкой диалога без идентификатора. Параметр принимает в себя обьект, но при создании диалога возвращается логическое значение.

![image](https://user-images.githubusercontent.com/56313646/188481354-8010d927-7477-4090-bbca-c38eacd945f3.png)

**Comment by The2Alert** [comment]
<p>Вот <a href="https://github.com/dev2alert/node-samp/blob/main/examples/9-player.ts">тут</a> показан принцип работы Dialog.response.</p>
<p>В Context API можно воспользоваться декоратором <a href="https://github.com/dev2alert/node-samp-decorators/blob/main/src/dialog.ts">DialogRes</a>.</p>
<p>В твоем случае можно воспользоваться событием onDialogResponse(response: DialogResponse): any; в твоем контексте.</p>
<p>Должно получиться что-то типа такого:</p>

```typescript
import {Player, DialogResponse} from "@sa-mp/core";

class MyContext extends Player.Context {
    // <...>
    public onDialogResponse(response: DialogResponse): void {
        switch(response.id) {
            case REGISTER_DIALOG: /* <...> */ break;
        }
    }
    // <...>
}
```
